application:
  port: 8000
  host: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5432
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  api_key: "d73cf446289ad30dd37b16003761a7a1-ca9eeb88-2024e546"
  timeout_milliseconds: 10000
